name: Publish

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write
  pull-requests: write

env:
  AWS_REGION: eu-west-2
  AWS_ACCOUNT_ID: "094954420758"

jobs:
  build:
    if: github.run_number != 1
    name: Build, version and publish
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 #v6

      - name: Build the test suite
        uses: DEFRA/cdp-build-action/build-test@dfb7dbaa4129b6e7e6b250c043d06628b32f8167
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
